apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: https://discordapp.com/api/webhooks/1369998535252250635/QsReEdlKO3ZDFdmw3fi6bYUcubpLj7re9EEQZsGi3KuFsSCcoFMw9KK7VHZ1DABTi_r3
