apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:mMzgpuh74jjd3AI61nkV5XbSzkHuMaGqD71AYMJQec1Fa7/oeiR5/a3LqTIHup/BDAJNDzt6Q2vgbj7UGeBNy7Q=,iv:PV4Zm5rOzWtWnL98JL+LBoJfSW984PgRgspybXU+/Zg=,tag:AQkqxGYIJOSqocT082pLyg==,type:comment]
    #ENC[AES256_GCM,data:GvKrYf5LGn24G3apF2xfsFvhgPgK6Lr2uLyz99StTqOQzqzWemfbPmbLKeE=,iv:f9bD1SInJiDn7FWMj6S5546ZreibqCiweeng3l2jE8A=,tag:8+6pHlU6IOVLk1azFzJ03w==,type:comment]
    VIP: ENC[AES256_GCM,data:NS+Nm7iWtsJbiTNM,iv:WJ+f8SbATcNsXMREdBLnEEfBHP2owu3E4TLgHtDz5AU=,tag:fNZGvg9dd8UTkdq2sw8KLg==,type:str]
    #ENC[AES256_GCM,data:9DRA2B3ID16v1SW8iTAUoLNqgx+AL2j6PFow,iv:ZuwvxE4zHjgkrJYuuuWD9epWsPFMCSVh6N7BNowh44Q=,tag:J+ELL4mt2n9NvhoJrODDqw==,type:comment]
    #ENC[AES256_GCM,data:Ysa9fvd3uGudbvTnW4XJIKB2nlHYmQUd8IXmKsaxvcQOnLVkDSl/IIautcO/DIBgNiybcIRcSX2MmzNrX7hrvCixj5Q4pROJ8SaORldXvacqfeMoPo3KyL0=,iv:WOiQS7xxQlXig98mQ4wO6DAMs/mLGXgKpmv0tffhAUY=,tag:nh0fjU9EavfDv8KS1Fgnvg==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:CtYmZVDqtDye+m0qxQ==,iv:oDJhueN7Wcgr8UKgyBWFuVwrMIh9zKGm5HB7dv5WN/A=,tag:CBk0C7OfTKuOaSSMi18hDQ==,type:str]
    #ENC[AES256_GCM,data:1DuCO7v6blFsCs4adiCPSUmkrzhe5uYQxitOwb3YoAAzgQ==,iv:DjJaEz7/aLnkh+zplqkV3Et/Y2ZqH4SU/xA0lKYFskQ=,tag:ZPHrlchGisZ3L+njwMdC1Q==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:+dDxJEKEmDb2rQU=,iv:jJDhCrArgEaLgqP4bqwDW7EK66vW3xFv93p+uXIAI2Q=,tag:ENfDxxgfSyQtW+SehgU8Hw==,type:str]
    #ENC[AES256_GCM,data:uiydziGYQS8g0ABjEJbOOF5JjBwv2aQyyoDqljAxWI1HeW7O3LOZJogayeuQB0M=,iv:6BtRNnnuwgulnpl3oIlXrrl2JHjNi/QVFraQfUIn9Dw=,tag:+2bejdrVIiVlb5sRPTkA9A==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:ayLw0Jsy170wWfoTCXQfi0vjViu080rcfQ==,iv:sWSuB7Mk8mpiQ2JaBVGOMlCaUwrZ214mAMlJ3D0TfFY=,tag:pge/HpA+sGgHyZvKwSoMaQ==,type:str]
    #ENC[AES256_GCM,data:LYMaqaAJc+DqHAgJGMLoTvxGL/cGf3Ypodk2/CUV4u0lQxKs2Gi7QvgSc4JCixQfClfFRZFLMjALJ6aT5Z6D0o+3wfJ2IxE0h6DTd5EZqmJJtQ==,iv:C92EMnnkXPRALUnZ0K9YsQ4c83cmwm9z3UvMpVi0ZKg=,tag:PGbvD9rQjiSXp/cxyC/JSw==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:l51+xmNvjnqNWofV,iv:Y915Yn5qZhAJWr9ujfmOjvyxLYO/7DWhG12tic4X/G4=,tag:TylGSguA+xnvQ2ZbFl944g==,type:str]
    #ENC[AES256_GCM,data:gLDyUmOm4tFiHRXVLT9lG4euVlGdN1xDPg4LH9O0d7jU,iv:+yIfPzrq9hsIjY6RYPEcK0810ZcXb4pnlrAhtkh7Zy4=,tag:wHjtC4/AUfeFKhXVvmsMxQ==,type:comment]
    BLOCKY_IP: ENC[AES256_GCM,data:bCyUFVsRTQ4p3qLf,iv:PrazJlXwm8Nb/Q5Qi7Ml0mIqhFXZ8LcVWgQKss5ge6c=,tag:bwGwk4QrLoLsiqOIhUzEbw==,type:str]
    #ENC[AES256_GCM,data:sXhrKVScQbgPg4ltRtEvozRlXiBKiQMYGBiDhURYZoOt1q2v78lENI/qWA2tusLBzm9fe9O9Kl00zaDMp2qT7UWw7IKelRY0syeMRZpxaRA=,iv:J9q1gdWDUam64gtwF4aSXab5uDO67RHXx5O2uI7wamA=,tag:EwmclSrGxVdQZZSET8Y2pA==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:S2Vy20W8nODMFnVQ,iv:QxRxENrmt1lI9cvVbB4YpLvFvt2ii7+P8rtuIPnTbjs=,tag:nk0ik2kcdCqxW65GDqMtLQ==,type:str]
    #ENC[AES256_GCM,data:dURaCDR7SoWQHLA9NwNNDuVslLFVIRGNOkAAdQB4maPPxX0BrkqkSpgdMlafnm4xM2+QUkgDs3ajYz5L+ywajnVZVvPyTZNPXz93xeAdqwd1fojWmLxZ,iv:HC/RieQFVL/6Ah6/mck932+WqNSzLlxNoQjgrM7T3/8=,tag:uI4221vFfxkMF4rspOswNQ==,type:comment]
    #ENC[AES256_GCM,data:Wf8N4Mp923AFeS9LhF56XK/BWflB5NfWA/rvk9S5FauPNgxWDa0ET99UOBD4kYbwY2UOVqCeDIXr8R27gXr1R62fA4lRSBw3BEsIWTUs8twqun0cLemulIxc6KN/XNXOLiRbNjL+OWtb/zAUndzedcK4WBLIOGL7jSsGyA==,iv:qhe1pXRCJXEZFHo714Tcu2whPSoFhol4hK/J9sIIi+k=,tag:DObxu92gaEZVEAxm0dbKiw==,type:comment]
    #ENC[AES256_GCM,data:VMp1i1Au1UNmx2//NI9LiM+KH63mWeASYNQEL7XCdHJu/5zbyLCDYLpEFz95q0zvcgwWTA0JS0u5NXQXlM8K7XhkG2JtFCWTjB+mv6QVzCs=,iv:o4yDpFp/Y+uH86KYP7sKzuiVDrrx09VDD1BLIpUzo98=,tag:ALmCecQVXg60b7yUywYmdA==,type:comment]
    #ENC[AES256_GCM,data:pREBTQouKp0Ckf/20yMmG5sCB2kWsRjFvoOkYSfpGWB40ats1Ds0CNlI2LYX50COGXPkTHVL,iv:t979QzU8AZCKbMsM8EvDcj0OHYUcJ1WaFCN+U9xJdbo=,tag:mSKNY3ImBQ8BG2sp+MDNeQ==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:qJXoYlAFM4nmUNvb/g==,iv:cyZT6Jz9e+psODZz5trDpoYy0Wmc3rB/rQE8pe+SkO4=,tag:vloWiyn8dEW557+aZgktfg==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:tWoOJAZScpJ0scwJ9GJFpRZqNYizCVRr,iv:iC9iQ7dMIDBOLb6xkUCQ20pZq8k4JfsZ2Ssr24lZUlM=,tag:hDaKTdUhOgQpw0RTJJxSJw==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:BFxF,iv:q8FJrWxHGdQXK2HFhzy4zjCIzs/MWqdsn4iu27Y2n18=,tag:EXWNfc9PTHGmGMIXWIDpFg==,type:str]
    #ENC[AES256_GCM,data:3phodWrV36eD2IrFTrsoVMdUarx379LwCqwHuXnxkroBlWBbsPOpmcwpeKaEXW8zESEpsi5K9bg=,iv:Z9Hja7ZEOO/LKuL4voQYTwADrL4i/goR5axzaJqg840=,tag:9N0UOlDlNoUcWKHQIeaalw==,type:comment]
    #ENC[AES256_GCM,data:e6dZZ+rZkEdOphEpLGXqsovnR9cFRKJY9Q==,iv:cSPtTDZcjoo4VIm5KMb3AWvVntvd+eEtKeAv/d8ScRA=,tag:9x0EtJvgR88FkDFSj4D4lg==,type:comment]
    #ENC[AES256_GCM,data:WTnVBj/kN00DskmqWWMrh7Y7lZVU4JHn6TV4bNewRZxf6hi5XBNb7SA6Rzu+T7yBCoN1G1S46w/HTwmzYN+bVc7TIf0yEjxhYYK2f54=,iv:KCBRcy1nheJeJXzm9yZ1PBgzvfGMzUopwl5DFPVVf8I=,tag:qJcAL5n4jznsnZ0pMEcTIA==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:K5cA4irt0vcnA3EQiZrIpBwKPOIJb9l44yrRkayUH7+DliUGCx4F7voIV3qDuWl2PQ==,iv:QwfRKiTgTeuNfwcwIID17u0h169nNh8u61v5nptf6Po=,tag:RYZ5veEHKpIlWuTxWsVdMQ==,type:str]
    #ENC[AES256_GCM,data:IqrlZ5u4j4uBCnPgr7LsTrzvLKJ5Pu2ZjnKMtC0OKcVjnmJ9SGcoA7xgPARP7gEtIq4sObrEjUN5ZjQNVTUz190m7M/5QQ4=,iv:YNABqHrmaOH6C+7k61JIJQn+ysAn/3DOA30fWj8Csts=,tag:TFbag7cWkh1SlVZwX2lXgw==,type:comment]
    #ENC[AES256_GCM,data:gpre+6XnZp86TFbeLRTGH/m2YcBZvX+AH4ZdPYf2ImBnW+pDyvViEbsxYK2mKLqBLN9PuGtf,iv:NfnMduoZbuRZDrRQMwH60xf8ONpSpRsITwcr+/oJgj0=,tag:NGRcOIAbsypPV8KZeOK0Fg==,type:comment]
    #ENC[AES256_GCM,data:osekas7DiVhEDA6Bh4VwvXJ3FezqPnrQIaBCOZIQYe6tidQ=,iv:qQjAMPlEOWsUQrEwUxmOpSdzRoHGVXV05MsyPj/i3Ew=,tag:a2BTy31v2lLgNtYKOXmDiQ==,type:comment]
    #ENC[AES256_GCM,data:WVuxAT/6yqA9uWr2nf1vfP9PLxZs/4+ksAwUfZOiRwwyv6mqakXY,iv:0Sz7G5wPqN6+IkBnRyilj/3O5lyeZSxCBzhHpFyLkHY=,tag:nCYquAdjAr0JBKOFpqM0bQ==,type:comment]
    THREADFIN_IP: ENC[AES256_GCM,data:iZ6VU7PWUa1XsGhc,iv:Y5yWwY4gKsoRUuq9OevMNdvq+cPGZEfU9fCjcOoYYqw=,tag:OwWYi9gT8SW/h0jjLWY9cg==,type:str]
    #ENC[AES256_GCM,data:WoLIUawZXunjCucjxWs=,iv:q8NnBZKrC/bDfxtZru0CnJVgbZEmel05tlAiYGSHN10=,tag:ZkwfgsNt7nU0YlEpgfT8Rg==,type:comment]
    PODNET: ENC[AES256_GCM,data:D7ELY6ggT6jargAp6A==,iv:0/xX+bMvbiYLP2rV7FAh7UUlzNq6AWKc8XYl77Z4lJA=,tag:gTdVEnWqa8wHBgM6fuQeUA==,type:str]
    SVCNET: ENC[AES256_GCM,data:Lgqr9olB27i3BlsawQ==,iv:Cz7vsqBDI+KB/8vmCnDFrn1F4K0advOUcOgxdG+AKSY=,tag:8hRD/02uUbSN+Hx4LWTs/A==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:Rw+2xQ==,iv:mo5DkFNIqTHiInZZvlMGL4ujIg+FvDeXfNe5lnF1UnU=,tag:KFaHSdOsYWwKhAiHKRmcXQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12kf7uw73efwudhh9mpnzcad6vq8l7plkrma0rqtc9wfrjv9p7qmswpnqq9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3V0tFd0ljMXl2UmNwRHdt
            RXhuVnZtN0VTeWJNdGsyMk5lR3pMUWV1b1dJCnIyd3ArYzllb1B1ZllSSEV2d0Z2
            R29rUkRYN2cvZjR5T2s3SllsTmdYQmsKLS0tIHVJdHVrUThqQmhjSUtsTGMzN05a
            S3ZDU2dXOHg5bGFUbUJ6dy9YWDRoOWMKy5nPs0VxfeeI6CSDROCet/PeXN692AAn
            McX1vBsJbwte8UruHwlyqpkfD1zvb9SRwAlwSOdCpe1meUki2tU40w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-04T03:33:09Z"
    mac: ENC[AES256_GCM,data:6m6JfazTYKTqUHSS5YuY5cKlcdX2+TYtIFQwoI0qbitskyEy1ls3lqCLVWoCEb87Reuy+5YUCtXbui/X8Bgpe3A1vnGrorGS7MuTjVsUtXLEEY/kvO9f1NZD1lF/gIgQ+krIoIaUoanrrjWqqyWLoo29goOY1FJqTA4wP9uWWVI=,iv:ff7Ne/hJ1bEeITCJYiVrDwybcrI/4CoRe8tGFFxiSSw=,tag:vw1BATO3TpKzuYWnoqieQg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
