apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:D4AQo5zjCzO7eEtZ41jazB11sww+PqhqJK8QzVLGdDwQvY4tfcgP6sRCHR3TlM0P8oDXDx+/uCHdgRTtmcSK86aKL7psxuAcC3feANVqAXGyd+T6MOq4SL7nLBxRS93Ep5R9iL6xqNsiW9M2V4/31FRgXUi5ht+ICyoElgUsBeDJDy7M+OUoNsUb3ZLwHAeZxmslYRTZcKjy0aYELTXN3ABfkMcQrzL1pzNlQeXhYQbVkt2NDNZR+/ZHllAzVjEZhFosRdygQ0EVhLdzQLmwgpoFzJSPjV8/92NRqkK/tK2XRT1ZRW3/pXcfexHsYMTFz6wjNbilpk5qUia1b/J9nMraJlHF0rUJC5ZQK5VNWyipDMxjFM9FiFDk9qWJvQfr,iv:VlBupaZ5ycrjNN0bjeR8jOJ5Qt70gqAf1Hl8vwOrLBE=,tag:aBDXqZAqDE2fJHxxyt8oEw==,type:str]
    identity.pub: ENC[AES256_GCM,data:C+6UEctGta0Lc7v2xowyIno8EzoowaB0AXFVKtNjGx0QJjLRee316LJoluZVtraxis1Ks6M9pDBR67pqGMu7393txEW3VN1C27ScxyeQxh4UbD6S42VaQhfHpKhGCoUxbW9SNXrZA5lKgqDpu9zSlLF6wEP8rWTAVx89kH/l0RlxZHwTrzso0RR2tMdh/pI3t+smdQf2ZGTJ7k906YH4ldP3KxiPvbSvgVnxDX4Hk5e6bkHn256qYN4THg9RQ/GQAbPeAB7z1515kw1Fdg==,iv:4rFh5HzxffEHda5SyQMq3SOmAqymfLWRL5fN69ZcWlw=,tag:HfKHd3qW/Kr/LMQc5rK1wA==,type:str]
    known_hosts: ENC[AES256_GCM,data:g+vEr7w31RsXZrPyhIm3pamCY9svjkadf8ckvHv1Fm1NwaNrM+LgUyFttHD8/6Tq/xjQ8qfLETMfHG7xTViIEGF7KrMSz5usOhXCagocrraK9b50PMEskLLyp1JZxLaK7LIw160N3joKM09/wRyIb2/sOo+c8vAxA8KTWWJAhtLI2nCXzOGTOW+Ii9Bl/G1lZvsazoroHmOEePtC6zlWsIoJNTvFNBa+FBW9,iv:O2CmVTsbVh8s7L6OHAeI3B+Xx0x+IlwuCSJnCO6O+R0=,tag:iHUYZF6r92SaVAXf1o3eiw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age12kf7uw73efwudhh9mpnzcad6vq8l7plkrma0rqtc9wfrjv9p7qmswpnqq9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bVk3cUtGK2F5WXUzbGYy
            OHZ5K3E4Q1J0a3d4dTAxQ1ZqOFB4aUxRcEVzCnVMT1NxVWlBaUo1VkhHVlJWRDRh
            N09wQmN5QmRwdGcxM0lDOVdiQnFGaUEKLS0tIDNPbERuMzMxZFpDNXpDdXZnNWhT
            amRJY01xMUx1cllXSzJwMkphRFlHb1kKIJp0sVH4rxSP2lffSK54SEHrQivoS2W/
            q8+Lrdrq3eTYq4E57XdKm6Cta3yWmf/5LiRFWK0UOLZK8uJ6yNkDew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-13T21:57:44Z"
    mac: ENC[AES256_GCM,data:9eJmO6+fYMc/8dVrD2ZyizEw2irWOg2TvKOys1/I8UqiiGI/oRC5hqbOWGWuRnASYdDnZgTVN4JNuVa2K7iDQNE6KJH3LhZ/tBLwrDnT8xbIuid8Z1js/a03WQG/o7mQlLK2hfQXTUeDu2h8ax0qzMnD3+x0FY3igeB+iPGFhVw=,iv:xxQepcq+VtDiATcR7mxg5rdYAG1JJs1RSJjC9OB3guI=,tag:JYhoiPX7tytgR3gUnLn1bg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
