apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:4pRtH4ywStwGK6HLQBsKv9vCQJRCKNcbDPw+krbG6cvQAQA5H53cxaVXIDbBwVF9EueU4808btDLYXaH4an6P8BfbIIvuxmtLB2Rrn0Vh0bWzVXL+j70AF2vXkQ8hk8lnZO4Jeikg/jhFrpCpq35Awaqvwi/XQMqaQHkEmQG9Pv0Bb7RvjLYeKf3Sl8TJo1+jk9lHNqNCfLJDgS0m3oY+HSDFC+GL/57JmeszVCBn39b3//wvw9HV9iy91t1vXqWYG0eOr9+z1HJmZH22ZRGm8PYe4T2NWY2VCsPDHkFg9LOs/iRWusKVYvFl8gUtXO8GxgEE/UsnIaBdZEkVyBlahSUXuCRNlaljQUN2RFt8BzFmk9VVv/pTsF5XhIGBfKr,iv:VKdf0hFENOtTYa4rwj29iugqIMQuvhIurwYJGuwmrzs=,tag:1ooNBpWb4YEiptJiHfBbng==,type:str]
    identity.pub: ENC[AES256_GCM,data:RkqYF/Cy9P4UAMkqY/xX/Uqm8QvfHy/2A9VDqdxcOqc1f8bWKPk5RxyKyU1vf1sHkxIc+qYHFXSrC/cIdPGOrrQbII8G6DsoPcVSL1SH4SxI3FXvdnpsZGHc5L51MrMPpInlQp0e6kueiFyqoG/tm1e9M9a8V8E3Q1YLBGXOnWK6dqTlpKS8n1q+5ZaD465JyLg+6E2wqMabeRoVRuYpOgI85H71Wv3VnipAPQq7uPCeMcbLBytRVxE7P3EQoYYlHbKg3Y4oZUUNPzK9hg==,iv:tHZ6rNGtxqfteI0P2cwd28ZMg+bPYj3YDw2xr0N1qxw=,tag:qMDBCFmva5PQy1jf0ouT5w==,type:str]
    known_hosts: ENC[AES256_GCM,data:9Xrc6EDQhliEn8KvSeGPcED8UsC9SGJjwBGrGQL1tCYqCaJyS93J78Te6lG5CxP2lCQ4F+/2jPmnXAAnVMsWzmc2FxymzRgitdIiypksvlD0DLg0IzhVL84YJbHoYVDGp0iOw/b9WL9dIwV6WwGa9v44sHMcVyX3t+2iYzvZEWx3Rhhp4Srg9ME7a7ra//EU9XTmMakxj8P0DXzMbyyJ2lq87mhDSAngwanp,iv:n/e4S8o/7RcjQ87FYNE2EFz7LVrDK58BMIV+Evcp0KE=,tag:hdkqbX9jEXqi6y3to6BiYg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12kf7uw73efwudhh9mpnzcad6vq8l7plkrma0rqtc9wfrjv9p7qmswpnqq9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMUtnUkY0dmdaY2srN0Vr
            Ry8zS1dhaVAvazBKcU5PTHZkZFJseUVnczM0CmtmSkpPY1JJWG02dWY1TWc5NHBM
            MFgwR1hzWE9mN1FJT3JCTkpwNkExZnMKLS0tIE1mV3J4ZW9QNXg4allLYlhNWUZT
            UGxranJOaVVHME5yVGpweTE5TE9zWDQKG5/hGRj6P4q14ei0jtGIfySbajJ4O37m
            8U84Au1tophWfuMDLWGv8bhMnQ2oAsLoy8/ujGLYr8q604suTSsgIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-04T03:33:09Z"
    mac: ENC[AES256_GCM,data:XpGZiuYl+XAnDTnAbe1IZLkLyAOD9snEH6w6toaUeJz/yfukKmK0elBkpaSA48M7qj17ZA37G3SKd3ydJSfyv4RzBjFMV+S83yNTIUzcgPBtTqN8c9H5tHO47SVTdezf4OyN1v7Ab4XdvRMvp3oy0ksdHAJr425/Qz1aBE6mAsY=,iv:FSA78TDV/lCrCBznoYg/igVewgEdr5fjYCQyU8S4RFE=,tag:sB1TbLXDuiSkjeC/rLhxwg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
