apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:sG9iyMCO3DcWHpzsdENw6ON4Xe5DLAvWZ5su8K+QVX3Y6h2R6PfYudkw+dcD+8UuhoJtX5wT9fkE1kKHppcX0b4QJ+T6sTcbnDOTXAyD+yDDog2+01uO6v7naLQTQlBZ+P9rt8Z1kEixGInW0XCgB8uxM+TqwUYMjc4cDo0vTksxt/eNzySvWieQbgi/nenkKdCWtdLcQDyVN3MD5c2TGSKI4MU5iWxHNDMJR9UWTS4JFBLMjg+YK7PrRZ/YgwYN49p/asnue91yTAgFVrIw9+DLYCvbHgcHJi3xKsCOl1RApIB4ANynzmm5mXoHTydUFOPBVo9JT97Z6x61Mbrizi2GuR4VIaDwHZJzuX4e2pDcXTaprZxTttZLu/lfUNAi,iv:NXKfJiGwbodcPQ0WhSMhzUiL8WyPvS+vlynwVHykqHc=,tag:cxoiRthGX/n3fVuVEi8+rA==,type:str]
    identity.pub: ENC[AES256_GCM,data:I6tDwH6dhsI1QsHjqVpbAJGX4CB8jzSQxdrY5r1/Zv4KLEBQlyOnlXyvefbhSeN0m77Q5R4wURDdT4Ti0XL2JdZEpjEqe0KkbQps9O68ixb6TOmq+6tAbdbLmGYXouj/UqDaR/2LGbvPjOEv+fYj2OBhpNWTyKInomd1fFShWQu0NtJ0NiyJWVKRv6OAEFdAU511Snnq9jiDQM4xfySi64pZHlGGfwYCIQ+LJjIaycb+cpN+6bOm4P993W1ZomXjDYux6bpfQzIydwTVxQ==,iv:mL1Dbzr9Vo9EYHDym+A7fiGEAog0KchfkMxVg8Nj4U0=,tag:UgxH+F0HGLGMDenIZmTgmw==,type:str]
    known_hosts: ENC[AES256_GCM,data:o4O/q/1zdL//bzbGeUSIaoKTANrMujWmlUB1/9JGjD2sy4fmy9HvQEPMM+jCFqtW6zEB+FddB4UF8Ft/EqMfkMd1gBszm2r9Ep7ojYWMKuW0g884ajIHQ9bQ8Jffb3jMNME+TCOAu7PLG6MH3ArvE364O/Y4BaHh66ipf6BnAQKgzBE3m3COLrnZH6pVIVP7ooBCys/NS4f0X3wQtN5o8uUQPrpjbZ+lc/8H,iv:D8GkRWpF+x2gl0ifl/mbFpfSKhoS1MtGGL0KYX5jbio=,tag:jxk3EF9G63YkZQUP5NWx2A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age12kf7uw73efwudhh9mpnzcad6vq8l7plkrma0rqtc9wfrjv9p7qmswpnqq9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSN0kzdjkwMHltMmRKL2ZY
            dE1vZlZ0UnEvRHU4U0FRR2xoMnZONDFpSlNFCmhaL0pDY0dhNm1WbTQyQk5HZ2Zz
            YjM5U3BFRmFrVHREUkJVNE96dU5TcmMKLS0tIG5UdWs2ZUhNUFdDeW1xSUZidWtJ
            aC9xSGNwZUxJc1VIanBiUm5nUU9Wc1EKsNr8FWlYbrYpsqriZ+W7+L4H63g1gfQ7
            9qs7aiL++W6BolipxH2mW641rgiwm5GMJ8ysaEBKXMDeQUzuiQkwFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-15T12:20:03Z"
    mac: ENC[AES256_GCM,data:mOMWp5HQVc+93jRJXiS4enh4rLwviCDLPr82C+a3AGNDyqLWJY1jtjd3SG4P3HnVCDAyPKUAvEguwNbWhAaaO1TGgBrqW6xJToKFa4cqXDoShzf4BM94TSnl4DnaXuicpV6TV04dTv7Yg7jD4yEzKuaV3ggUA34Y4gYkct5mcf8=,iv:daDe9qCTVozQt8dSolaRiVygXQnnuToSRIzbczpD3lE=,tag:rpj4A3w4UPPVTwFPItV6kQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
