apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bytestash
  namespace: bytestash
spec:
  interval: 15m
  chart:
    spec:
      chart: bytestash
      version: 2.4.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    ingress:
      main:
        enabled: true
        ingressClassName: external
        integrations:
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: bytestash.${DOMAIN_0}
    env:
      JWT_SECRET: "${BYTESTASH_JWT}"
